name: Release PyPI Package
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    environment: release
    permissions:
      contents: read
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: python -m pip install poetry --user

      - name: Build and publish to PyPI
        run: pypa/gh-action-pypi-publish@release/v1
