name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    environment: test

    strategy:
      matrix:
        python-version: [ '3.10', '3.12' ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Set up Python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install poetry && python -m poetry install

      - name: Test
        run: ./run_tests.bash

      - name: Generate coverage JSON
        run: python -m poetry run coverage json

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
